export const ICONS = {
  FARM: '🌾',
  SCAN: '📷',
  HEALTH: '🩺',
  WEATHER: '☁',
  HEATWAVE: '🌡️',
  TRACTOR: '🚜',
  MARKET: '📈',
  GRAIN: '🌾',
  WATER: '💧',
  TRANSPORT: '🚛',
  PROFILE: '👤',
  HOME: '🏠',
  SUCCESS: '✅',
  WARNING: '⚠️',
  ERROR: '🔴',
  PHONE: '📞',
  ROBOT: '🤖',
};
