"""add_password_hash_to_farmers

Revision ID: 2b7b2df2dcfd
Revises: 6794987c5f0d
Create Date: 2026-08-01 13:55:02.997467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b7b2df2dcfd'
down_revision: Union[str, Sequence[str], None] = '6794987c5f0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmers', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farmers', 'password_hash')
    # ### end Alembic commands ###
