"""Initial schema

Revision ID: 6794987c5f0d
Revises: 
Create Date: 2026-08-01 11:27:17.093782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6794987c5f0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_code', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('crop_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_sessions_session_code'), 'ai_sessions', ['session_code'], unique=True)
    op.create_index(op.f('ix_ai_sessions_user_id'), 'ai_sessions', ['user_id'], unique=False)
    op.create_table('disease_knowledge_base',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('disease_code', sa.String(), nullable=False),
    sa.Column('disease_name', sa.String(), nullable=False),
    sa.Column('crop_type', sa.String(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('symptoms_json', sa.Text(), nullable=True),
    sa.Column('causes_json', sa.Text(), nullable=True),
    sa.Column('prevention_json', sa.Text(), nullable=True),
    sa.Column('chemical_treatment', sa.Text(), nullable=True),
    sa.Column('organic_treatment', sa.Text(), nullable=True),
    sa.Column('government_advisory', sa.Text(), nullable=True),
    sa.Column('image_icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disease_knowledge_base_disease_code'), 'disease_knowledge_base', ['disease_code'], unique=True)
    op.create_table('farmers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('crop_type', sa.String(), nullable=True),
    sa.Column('land_size_acres', sa.Float(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('grades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('farmer_id', sa.String(), nullable=True),
    sa.Column('crop', sa.String(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('avg_grain_length_mm', sa.Float(), nullable=True),
    sa.Column('moisture_damage_percent', sa.Float(), nullable=True),
    sa.Column('foreign_matter_percent', sa.Float(), nullable=True),
    sa.Column('grain_count', sa.Integer(), nullable=True),
    sa.Column('recommended_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harvest_knowledge_base',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('crop_type', sa.String(), nullable=False),
    sa.Column('grade_standards_json', sa.Text(), nullable=True),
    sa.Column('quality_parameters_json', sa.Text(), nullable=True),
    sa.Column('storage_best_practices_json', sa.Text(), nullable=True),
    sa.Column('government_mandate', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvest_knowledge_base_crop_type'), 'harvest_knowledge_base', ['crop_type'], unique=True)
    op.create_table('harvest_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_code', sa.String(), nullable=False),
    sa.Column('passport_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('crop_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_harvest_sessions_passport_id'), 'harvest_sessions', ['passport_id'], unique=True)
    op.create_index(op.f('ix_harvest_sessions_session_code'), 'harvest_sessions', ['session_code'], unique=True)
    op.create_index(op.f('ix_harvest_sessions_user_id'), 'harvest_sessions', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('link_url', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('farmer_id', sa.String(), nullable=True),
    sa.Column('disease_label', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('healthy', sa.Boolean(), nullable=True),
    sa.Column('remedy', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('farmer_phone', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=True),
    sa.Column('message_text', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crop_scans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('image_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_per_day', sa.Float(), nullable=False),
    sa.Column('price_per_hour', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('village', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('operator_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grain_scans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['harvest_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('recommendation_label', sa.String(), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('suggested_wait_weeks', sa.Integer(), nullable=True),
    sa.Column('min_estimated_price', sa.Float(), nullable=False),
    sa.Column('max_estimated_price', sa.Float(), nullable=False),
    sa.Column('price_source', sa.String(), nullable=True),
    sa.Column('price_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['harvest_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('storage_type', sa.String(), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('risk_label', sa.String(), nullable=True),
    sa.Column('actionable_guidance', sa.Text(), nullable=True),
    sa.Column('humidity_limit_pct', sa.Integer(), nullable=True),
    sa.Column('temp_limit_c', sa.Integer(), nullable=True),
    sa.Column('pest_precautions_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['harvest_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatment_recommendations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('chemical_treatment', sa.Text(), nullable=True),
    sa.Column('organic_treatment', sa.Text(), nullable=True),
    sa.Column('preventive_measures_json', sa.Text(), nullable=True),
    sa.Column('spray_window', sa.String(), nullable=True),
    sa.Column('recovery_days', sa.Integer(), nullable=True),
    sa.Column('action_steps_json', sa.Text(), nullable=True),
    sa.Column('is_kb_grounded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('booking_code', sa.String(), nullable=False),
    sa.Column('equipment_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('requester_id', sa.String(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('land_size_acres', sa.Float(), nullable=True),
    sa.Column('operator_required', sa.Boolean(), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('village', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_code'), 'bookings', ['booking_code'], unique=True)
    op.create_table('disease_predictions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('disease_name', sa.String(), nullable=False),
    sa.Column('disease_code', sa.String(), nullable=False),
    sa.Column('healthy', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('affected_area_pct', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('inference_time_ms', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['crop_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('moisture_status', sa.String(), nullable=True),
    sa.Column('moisture_range', sa.String(), nullable=True),
    sa.Column('broken_grain_pct', sa.Float(), nullable=True),
    sa.Column('foreign_matter_pct', sa.Float(), nullable=True),
    sa.Column('discoloration_pct', sa.Float(), nullable=True),
    sa.Column('size_uniformity', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('inference_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['grain_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quality_assessments')
    op.drop_table('disease_predictions')
    op.drop_index(op.f('ix_bookings_booking_code'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('treatment_recommendations')
    op.drop_table('storage_recommendations')
    op.drop_table('market_assessments')
    op.drop_table('grain_scans')
    op.drop_table('equipment')
    op.drop_table('crop_scans')
    op.drop_table('voice_alerts')
    op.drop_table('scans')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_harvest_sessions_user_id'), table_name='harvest_sessions')
    op.drop_index(op.f('ix_harvest_sessions_session_code'), table_name='harvest_sessions')
    op.drop_index(op.f('ix_harvest_sessions_passport_id'), table_name='harvest_sessions')
    op.drop_table('harvest_sessions')
    op.drop_index(op.f('ix_harvest_knowledge_base_crop_type'), table_name='harvest_knowledge_base')
    op.drop_table('harvest_knowledge_base')
    op.drop_table('grades')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_disease_knowledge_base_disease_code'), table_name='disease_knowledge_base')
    op.drop_table('disease_knowledge_base')
    op.drop_index(op.f('ix_ai_sessions_user_id'), table_name='ai_sessions')
    op.drop_index(op.f('ix_ai_sessions_session_code'), table_name='ai_sessions')
    op.drop_table('ai_sessions')
    # ### end Alembic commands ###
